import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from './toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'AppCreate Next ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className={inter.className} >
        {children}
        <Toaster></Toaster>
      </body>
    </html>
  )
}
